ENV_PREFIX = "PADWAN_PROXY_"
PADWAN_API_KEY_ENV = "PADWAN_API_KEY"
PADWAN_BASE_URL_ENV = "PADWAN_BASE_URL"
DEFAULT_TIMEOUT = 3600.0
DEFAULT_STREAM_RETRIES = 1
DEFAULT_LAYA_MODEL = "convaiinnovations/laya"
DEFAULT_APPROVAL_CONFIDENCE = 0.99
